name: Sonny Huynh
description: Quick tips, guides, reviews and rants relating to software development
url: https://www.sonnyhuynh.com

author:
    name: Sonny Huynh
    pronunciation: (sun-ee win)
    email: sonny@sonnyhuynh.com
    github: sonnyhuynh
    linkedin: sonnyhuynh

source: src

analytics:
    id: UA-33823626-1

plugins:
- jekyll-sitemap
