name: Sonny Huynh
description: Quick tips, guides, reviews and rants relating to software development
url: http://www.sonnyhuynh.com

author:
    name: "Sonny Huynh"
    email: sonny@sonnyhuynh.com
    github: sonnyhuynh
    twitter: sonny_huynh
    linkedin: sonnyhuynh

highlighter: rogue
permalink: /:title/
images: /assets/posts

paginate: 3
paginate_path: "page/:num/"

exclude: [
"README.md",
"CNAME",
"Gemfile*",
]

analytics:
    id: UA-33823626-1

comments: true
disqus_shortname: sonnyhuynh

gems:
- jekyll-sitemap
- jekyll-paginate

