name: Sonny Huynh
description: Quick tips, guides, reviews and rants relating to software development
url: http://www.sonnyhuynh.com

author:
    name: "Sonny Huynh"
    email: sonny@sonnyhuynh.com
    github: sonnyhuynh
    twitter: sonny_huynh
    linkedin: sonnyhuynh

markdown: redcarpet
pygments: true
permalink: /:categories/:title
images: /assets/posts

analytics:
    id: UA-33823626-1