name: Sonny Huynh
url: http://www.sonnyhuynh.com

author:
    name: "Sonny Huynh"
    description: "sonny is awesome"
    email: sonny@sonnyhuynh.com
    github: sonnyhuynh
    twitter: sonny_huynh
    linkedin: sonnyhuynh

markdown: redcarpet
pygments: true
permalink: /:title
images: /assets/posts

analytics:
    id: UA-33823626-1